{
 "title": "flotta",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Devices management", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Flotta objects count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_object_counts{resource=\"edgedevices.management.project-flotta.io\"}",
     "legendFormat": "edge devices"
    },
    {
     "expr": "etcd_object_counts{resource=\"edgedeployments.management.project-flotta.io\"}",
     "legendFormat": "edge deployments"
    }
   ]
  },
  {
   "title": "Edge devices registration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flotta_operator_edge_devices_unregistration{namespace=\"flotta\", pod=~\"flotta-operator-controller-manager-.*\", job=~\"flotta-operator-.*\"})",
     "legendFormat": "unregistered"
    },
    {
     "expr": "sum(flotta_operator_edge_devices_failed_registration{namespace=\"flotta\", pod=~\"flotta-operator-controller-manager-.*\", job=~\"flotta-operator-.*\"})",
     "legendFormat": "failed to register"
    },
    {
     "expr": "sum(flotta_operator_edge_devices_successful_registration{namespace=\"flotta\", pod=~\"flotta-operator-controller-manager-.*\", job=~\"flotta-operator-.*\"})",
     "legendFormat": "registered"
    },
    {
     "expr": "flotta_operator_edge_devices_patch_duration_milliseconds"
    },
    {
     "expr": "flotta_operator_edge_devices_patch_status_duration_milliseconds"
    }
   ]
  },
  { "title": "Flotta Operator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"flotta\",pod=~\"flotta.*\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_cpu_usage_seconds_total{namespace=\"flotta\",pod=~\"flotta.*\"})",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Transmit Data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_network_transmit_bytes_total{namespace=\"flotta\",pod=~\"flotta.*\"})",
     "legendFormat": "bytes transmitted"
    },
    {
     "expr": "sum(container_network_receive_bytes_total{namespace=\"flotta\",pod=~\"flotta.*\"})",
     "legendFormat": "bytes received"
    }
   ]
  },
  {
   "title": "network",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(haproxy_backend_response_errors_total{exported_namespace=\"flotta\"})",
     "legendFormat": "response errors"
    },
    {
     "expr": "sum(haproxy_server_downtime_seconds_total{exported_namespace=\"flotta\"})",
     "legendFormat": "server downtime"
    },
    {
     "expr": "sum(haproxy_backend_http_average_connect_latency_milliseconds{exported_namespace=\"flotta\"})",
     "legendFormat": "latency"
    }
   ]
  }
 ]
}